### ISSUE TITLE
Issue with dot in file name that is not an extension

### ISSUE THREAD

**Issue by kevinlang** [lumeland/lume#132]
If I have a markdown post named `blah.6.md`, it will generate an HTML file as usual, but the out path will be `_site/blah.6`. 

If I change it to `blah-6.md`, it will correctly generate the HTML file at `_site/blah-6/index.html`

**Comment by oscarotero** [comment]
This is the expected behavior. If the filename has a sub-extension, it's used to generate the output filename, instead of html. For example, `styles.css.njk` is a nunjucks file that generates a css file (`styles.css`).

If you want to avoid this, use the `url` variable in the front matter:

```md
---
url: /blah.6/
---
```

If you want to apply this automatically to all files in this directory, create a `_data.js` file with the following code:

```js
export function url(page) {
    return `${page.src.path}/`;
}
```
