### ISSUE TITLE
Compilation of Layouts for Faster Builds

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#14]
Many template engines (like Eta) support compilation of a template into a function which can make it faster. What if we allowed compilation with layouts to allow faster builds? Some template engines don't support this, so we could still keep the run every time rendering open as an option.

**Comment by oscarotero** [comment]
Yep, sure. Performance is super important.
Do you have any idea of how to implement this? If you want to contribute with a PR, that would be great.

Precompiled templates should be updated if we detect changes in the files (with `--serve`). For example, nunjuks has an internal cache that does not update so I had to clean it manually before every build https://github.com/lumeland/lume/blob/master/engines/nunjuks.js#L14

**Comment by shadowtime2000** [comment]
I think I can implement this with a cache based on layout filepaths (possibly expand to just templates everywhere?) to hold the functions. Yeah, I am going to have to look into updating precompiled templates on detecting changes.

**Comment by oscarotero** [comment]
Nice! Thank you.
FYI, this is the function called to perform an update after detecting changes: https://github.com/lumeland/lume/blob/master/site.js#L232
This function receives an array of files that have changed, in order to be reloaded again (I know, with Typescript it would be more obvious :) and finally build the site again.
Maybe we can pass this array of files to every template engine used, so they can update its internal cache if they need to.

**Comment by oscarotero** [comment]
Now that precompilation and cache was implemented in nunjuks, eta and pug, I'm closing this.
