### ISSUE TITLE
Use esm.sh Nunjucks?

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#16]
I was wondering if you will switch to use [esm.sh](https://esm.sh) for Nunjucks.

**Comment by probins** [comment]
+1 from me (assuming it works 😄). My experience of forks is that they are easy to create, but not at all easy to maintain (though Nunjucks is probably pretty stable and won't change very much).

**Comment by oscarotero** [comment]
Yes, it's an option.
In fact, I'm using a fork of a fork (because the [original fork](https://github.com/denjucks/denjucks) seems like is not maintained anymore).
I did some changes to that fork, like removing some dependencies that was failing. Compare the [deps file of my fork](https://github.com/lumeland/denjucks/blob/master/src/deps.js) with the [original file](https://github.com/denjucks/denjucks/blob/master/src/deps.js), the only dependency is a Deno std library. So I feel that my fork is pretty stable.

The advantages to switch to esm.sh is that we can update anytime to use new features and improvements of the original nunjucks library. But the cons are that we are not really using the original library, but an autogenerated version that can introduce bugs and load more javascript (due dependencies and stuff).

I think that we can continue using the fork for now but keeping a eye [on the changelog of the original Nunjucks](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md). When the new version is released, we can reconsider again if making the change worth it.

**Comment by probins** [comment]
Can you use the browser version of Nunjucks? There are 2 basic issues here, right? Converting code from CJS to ESM; converting Node-specific functions like fs. The browser should use standard js with no dependency on Node-specific functions. The current min.js has a UMD wrapper, which would need to be changed to `export default`. The best is for Nunjucks to produce ESM output, but downloading and editing the wrapper on each release should be easier than trying to maintain a fork.

**Comment by oscarotero** [comment]
The browser version uses ajax to load the templates (You can [see the code here](https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/web-loaders.js#L61)). Deno does not support XMLHttpRequest and [won't support it](https://github.com/denoland/deno/issues/2191) (it support `fetch`, a more modern API). And even if it were suported, it wouldn't be so efficient as using the filesystem API.

**Comment by probins** [comment]
ok. A pity. I suppose the underlying problem is that so much of the JS code out there is out-of-date. I see Nunjucks' build process is still using uglifyjs, which doesn't support ES2015, let alone more modern JS. Ideally, all this code would be updated, but that's a mammoth task.

**Comment by oscarotero** [comment]
Automatic conversors like esm.sh do not work always. For example, I had to port Pug to Deno by myself because the conversion from esm.sh conflicts with the Typescript of Eta: https://github.com/lumeland/lume/issues/18
So the most stable/reliable solution is using a fork or port even if they are not updated so often as the original library.
