### ISSUE TITLE
`Engine.render()` and `Engine.renderSync()` take generator as its first argument

### ISSUE THREAD

**Issue by aiotter** [lumeland/lume#168]
When `Page` is a generator, `Engine.render()` and `Engine.renderSync()` take generator as its first argument, and returns generator which yields `Data`.
I don't feel this intuitive. They would better to take an iterated content and data as its argument, and returns `string`.

Also, `Engine.render()` can return generator, on the other hand, `Engine.renderSync()` cannot. I don't think the typing here is correct.

**Comment by oscarotero** [comment]
When the page content is a function, it returns the result. The special use case of generators is to generate one page for every yield (as you can see here: https://github.com/lumeland/lume/blob/master/core/renderer.ts#L51-L82)

This is behavior is intentional as you can see in the docs: https://lumeland.github.io/core/pagination/

**Comment by aiotter** [comment]
Sorry, I don't fully understand what you mean.
You said when the raw page content from Loader is a function, then the page content will be the returned value of the function after rendering. Is my understanding correct?

I still don't know why you want the Engine to handle generators. Engine is, in my understanding, responsible for modifying the raw content from the Loader to create a string (or something convertible to string by `.toString()`), which is generally a content of HTML files or assets.
Do you do this because you think generators from Loader itself should be better to be passed to the Engine? I cannot imagine the case this behaviour is needed.

For me, this sounds simpler (here, Engine is a function of `page content and data -> page content`):
```
input file -- [Loader] --> Generator<Data> -- [iterate] --> multiple Data -- [Engine] --> multiple Pages
```

Comparative to the current flow (Engine is a function of `Generator<Data> -> Generator<Data>` ):
```
input file -- [Loader] --> Generator<Data> -- [Engine] --> Generator<Data> -- [iterate] --> multiple Pages
```

**Comment by aiotter** [comment]
And if this behaviour is intensional, you would better change the signature of `Engine.renderSync()`. Currently it can only return string, but it's better to return `GeneratorFunction` which returns `Generator<string>` as well.

**Comment by oscarotero** [comment]
The automatic page creation using generators is designed to cover any use case.
The most obvious one is pagination. In this example of paginated result: https://github.com/lumeland/base-blog/blob/master/archive.tmpl.js we need to get all pages `type=post` and create new pages with the result. So we are creating new pages based on the existence of other pages.

Other example is creating a page for every tag: https://github.com/lumeland/base-blog/blob/master/tag.tmpl.js Depending on the tags assigned to the existing pages, new pages will be automatically created.

We also can use the `renderOrder` option depending on if we need to create new pages after or before render other pages.

The generator function to create new pages can access to the contextual `_data` and other global values like `search` or `paginate`, filters, etc. In other words: it has the same arguments of regular pages. The only difference is it returns a generator instead of a string. This is why it uses an Engine for that, because the context is the same. And this is why the pages creation is managed by the renderer, because it's part of the rendering process. If you're curious about how Lume works internally, take a look to this explanation: https://lumeland.github.io/advanced/order-of-operations/

I don't understand what's the problem with this. Do you have a specific use case blocked by this behavior?

**Comment by oscarotero** [comment]
> And if this behaviour is intended, you would better change the signature of Engine.renderSync(). Currently it can only return string, but it's better to return GeneratorFunction which returns Generator<string> as well.

`renderSync` is used only for components, not to render/generate pages. This is why it should return `string` or objects with `toString()`

**Comment by aiotter** [comment]
I know the use case of generators is important and useful. I just wonder the generation of the data is `Engine`'s job. And I also doubt it is consistent that Engine usually returns just a `string`, and sometimes `GeneratorFunction` which returns `Generator<Data>`. If it usually returns `Data` and sometimes `Generator<Data>`, it is consistent.
I didn't know that `Engine` is able to take and return generator until I implement `tag.tsx` which imitates your `tag.tmpl.js`. This is not only because the document about pagination does not mention the `Engine` interface, but because the `Engine.render()` takes `unknown` and returns `unknown` so that I wasn't able to predict the behaviour by its signature.

> Do you have a specific use case blocked by this behavior?

I wrote a plugin which registers an `Engine` for `.jsx` and `.tsx`, using [Nano JSX](https://nanojsx.io) as a renderer. It was working as intended until I wrote `tag.tsx`. While the `Engine` had `#render()` which took only `Nano.Component | Nano.FC` (the former is a class component and the latter is a function component) as its first argument, it would not work for `GeneratorFunction` from `tag.tsx`. So I had to write a special if-clause for generator. I didn't believe this is intended, so I regarded it as a bug or something.

The basic structure of my engine is:
```ts
export class NanoJsxEngine implements Engine {
  render(content: Nano.Component | Nano.FC | AsyncGeneratorFunction, data: Data) {
    if (isGenerator(content)) {
      // deno-lint-ignore no-this-alias
      const nanoEngine = this;
      return (async function* (generator: AsyncGeneratorFunction) {
        for await (const data of generator() as AsyncGenerator<Data>) {
          const content = nanoEngine.renderSync(data.content as Nano.Component, data);
          yield {content, ...data}
        }
      })(content as AsyncGeneratorFunction);
    }
    return Promise.resolve(this.renderSync(content, data));
  }

  renderSync(content: Nano.Component | Nano.FC, data: Data): string {
    if (!data.children && typeof data.content === "string") {
      // we are rendering layout
      const doc = createDocumentFragment(data.content);

      const elements = Array.from(doc.childNodes)
        .filter((node) => node.nodeType === NodeType.ELEMENT_NODE)
        .map((node) => {
          node.toString = () => (node as Element).outerHTML;
          return node;
        }) as Element[];
      data.children = elements;
    }

    const { children, ...props } = data;
    if (Array.isArray(children)) {
      return Nano.renderSSR(() => Nano.h(content, props, ...children));
    } else {
      return Nano.renderSSR(() => Nano.h(content, props, children));
    }
  }
}
```

---

> `renderSync` is used only for components, not to render/generate pages.

Oh thank you, I didn't know that. You can make it clear on the function comment that `Engine.render()` is for pages and `Engine.renderSync()` is for components. Currently the comments only say 'Render a template' and 'Render a template synchronous' (maybe a typo of 'synchronously').

**Comment by oscarotero** [comment]
This is my first project using Typescript so I'm sure there are a lot of room for improvement for types (I greatly appreciate help for this).

`Engine.render` can return different things, that's the reason of `unknown` as return type, because it's almost impossible to cover all of them:

- Most template engines works with strings (nunjucks, markdown, pug, liquid, etc).
- There are other engines that don't work with strings natively (like React or Nano JSX, that returns objects).
- It would be technically possible to have a engine to generates binary files (pdf, images, videos, sound, etc). Usually image transformation is done with processors, but it could be possible to have a engine to output binary content. Imagine a engine that reads a music sheet and generate a sound file.
- Some template engines are sync and asynchrounous, others are only synchrounous.
- And finally we have the Generator use case.

In short, the return type could be a a string, JSX object (depending on the library), Int8Array, Generator, AsyncGenerator or a Promise returning any of the previous types.

In your example, I see some issues:

- The engine converts the result to string with `renderSSR`, but this is not always needed (for example a jsx page using a jsx layout). The React engine, [define the `toString()` property](https://github.com/lumeland/lume/blob/master/plugins/jsx.ts#L46) to the returned object to make sure it is converted to string only when it's needed, in order to improve the performance.
- This is just a small detail, but you don't need `Promise.resolve`. `render()` is not required to be async.
- I'm not sure if in your example you take into account pages that exports a jsx object and a function returning a jsx object. For example:

```jsx
// Exports a jsx object
export default <h1>Hello world</h1>;
```

```jsx
// Exports a function that generates a jsx object
export default (data) => {
 return <h1>Hello {{ data.name }}</h1>;
}
```

In React engine, if the content is a function [it's executed passing the data and helpers as arguments](https://github.com/lumeland/lume/blob/master/plugins/jsx.ts#L40). In this way, if the function returns a generator, it's used to generate more pages automatically, and if it's a JSX element, it's rendered as string when needed (thanks to the `toString()` property).

`Engine.renderSync` is used for more concrete use cases (for now only components, that requires to be sync) but the behavior is pretty similar. In this case, it's important to not return strings, so the components could be used as regular JSX components. For example:

```jsx
export default function (data) {
    const { comp } = data;

    return <h1>To continue, <comp.Button>Sign up</comp.Button></h1>;
}
```

In this example (it's React, I guess Nano works in similar way) Lume components are used as React components. If it returned a string, it wouldn't work.


> You can make it clear on the function comment that Engine.render() is for pages and Engine.renderSync() is for components. Currently the comments only say 'Render a template' and 'Render a template synchronous' (maybe a typo of 'synchronously').

Yes good point. I had doubts about name it `renderComponent` instead of `renderSync` but finally inclined by the latest because it's more generical name and maybe it can be reused for other purposes in the future. But this could be clarified in the comments.

**Comment by aiotter** [comment]
I understand the reason why the returning type have to be unknown.
Then what needed may be a fine document for creating document about Engine interface. I had to learn it by reading the standard plugins in this repository, and it seems I had much more to know about it.

As for my JSX engine, Nano JSX already uses `Component#toString` for rendering it, so I wasn't able to override it for Lume.
And you cannot export the result of function components, or even call them by yourself. Nano JSX require `document` variable in global scope to render them. This variable is defined by default in browsers as you know, and while rendering on deno, Nano JSX will define it inside `Nano.renderSSR()`.
I don't want to render the components twice while rendering layouts, but I have no idea better than that.

**Comment by aiotter** [comment]
Anyway, now I know the current interface of `Engine.render()` and `Engine.renderSync()` is designed as intended. You can close the issue. Thanks for clarifying!
