### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#21]
It would be great to see some build time benchmarks compared to popular SSGs such as Jekyll and 11ty. @probins did share the speed increase in his sites build time compared to Jeykll.

**Comment by probins** [comment]
The times I posted were the total time setting up GitLab Pages, where much of the time is spent loading the Docker image and deploying the pages, not just running Lume. Deno programs are slim by design. To run Lume, you just need Deno and not much else. So you can use a small Docker image such as Alpine Linux with Deno already included. For Jekyll, you have to use the Ruby image, which is a lot larger and takes a lot longer to load. Jekyll also has a lot more baggage. Node is much the same: you have to spend a lot of time installing a large number of 'required' packages, much of which you probably don't need. You could of course create your own custom Docker image with everything you need already loaded, which would be faster to run.

I suppose it depends on what you want to compare. In my case, I'm interested in the total time from `git push` to deployment. If you just want comparisons of actual run time, you would install everything first, and then run the different systems one after another.

**Comment by oscarotero** [comment]
I did some tests locally using a clone of this repo: https://github.com/seancdavis/ssg-build-performance-tests (disabling nuxt, next and gatsby due they are incredible slow).
I'll add the repo to this organization, if you want to take a look and play with it.

**Comment by oscarotero** [comment]
I've created this repository with the code to run benchmarks and the first results:
https://github.com/lumeland/benchmark

(I wasn't able to make work the [other repository](https://github.com/seancdavis/ssg-build-performance-tests))

Hugo is unbeatable, but lume is in second position, except with big sites (10,000 pages) that jekyll seems more performant.
