### ISSUE TITLE
Inline plugin does not respect additional style tag attributes

### ISSUE THREAD

**Issue by jrson83** [lumeland/lume#246]
When using the [inline plugin](https://lume.land/plugins/inline/) with `style` tag to inline CSS, the plugin removes the actuall `style` tag from DOM and [creates a new one](https://github.com/lumeland/lume/blob/master/plugins/inline.ts#L108).  This has the consequence that additional attributes are not considered or removed. For `script` tags this is not the case, since the actuall script tag gets just modified.

The plugin should respect additional attributes like `nonce="whatever"` and keep those. An example of this is the use of the `nonce` attribute for the [CSP](https://content-security-policy.com/examples/allow-inline-style/).

**Comment by oscarotero** [comment]
`link` and `style` elements are of different types, so they cannot share all attributes. But I'm agree that some attributes like `nonce`, `id` or `class` must be keept.

By the way, I just realized that the attribute `media` is not taken into account. The expected behavior is the css code must be wrapped by a `@media` rule. For example:

```html
<link rel="stylesheet" media="print" href="print.css" inline />
```
should become to:
```html
<style>
@media print {
...
}
</style>
```

**Comment by oscarotero** [comment]
Fixed.
