### ISSUE TITLE
Allow Plugin to Add JS to Build Output

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#25]
This would be great for plugins for frameworks.

**Comment by probins** [comment]
I'm currently using afterBuild functions, but I too have thought that conceptually this sort of thing is part of the build. Scripts for zipping a file or deploying the output are clearly afterBuild processes, but building js files is much the same concept as building html.

**Comment by oscarotero** [comment]
Mmm, I'm not sure to understand.
Do you mean allow to load and bundle javascript files? This is something that can be done now with the `bundler` plugin (it uses the `Deno.bundle()` function to build the output).

**Comment by probins** [comment]
Yes, I think I may have misunderstood too. Examples please.

If we're talking about bundling, `deno bundle` is very basic, and currently doesn't minify. Rollup, as used by Denopack, is very mature, does tree-shaking and code splitting, and has a large number of options, such as producing sourcemaps.

**Comment by oscarotero** [comment]
The plugin is very simple: https://github.com/lumeland/lume/blob/master/plugins/bundler.js

It only configures your site to load js and ts files as assets and then register a processor to tranform the content of these files using `Deno.bundle()`. It's an experimental plugin, I'm agree that `deno bundle` is not mature enough.

You don't need this plugin for this, because, as you can see, it's very simple. Plugins are just simple intefaces to configure your site, but you don't need them to register new loaders, processors, etc. In your `_config.js` file you can do the following:

```js
import textLoader from "https://deno.land/x/lume/loaders/text.js";

// Load *.ts and *.js input files as plain text
site.loadAssets([".ts", ".js"], textLoader);

// Process .ts and .js output files with this function
site.process([".ts", ".js"], processor);

//The function to process every ts/js file:
function processor (file) {
    const sourceFile = file.src.path + file.src.ext;
    let content = file.content;

   //Transform the content with your favorite tool
   content = myBundler(sourceFile, content);

   //Save the result in the file
   file.content = content;
}
```

Note that `loadAssets` will load all `.ts` and `.js` files in your site. If you want to load only the main file (because all imported files will be included in this file by the bundler, you have save the other files in an ignored folder. This folder can starts with `_` (for example: `_includes`) or you can ignore them with `site.ignore("my-folder-name")`.

**Comment by probins** [comment]
the standard convention is to have source code in `src` or `lib`, so you could ignore that and have one js file in your site folder that does `import from 'src/whatever.js'`. I'll try that out for running denopack. I think it would probably be better to be able to run a bundler on just one file, rather than everything with a `.js` extension.

I've just tried out `deno bundle`, and find it has a major issue. When you import modules and then run something, it should bundle the imported modules first and then your code, so any initialisation in the imported modules is run first. But, for some reason, it put some of the imported initialisation after my code in the bundle, so my code failed as the initialisation hadn't run. Duh!

**Comment by shadowtime2000** [comment]
@oscarotero @probins Sorry, I should have clarified on what I mean. I am talking about frontend frameworks with SSR support. What would happen is it would generate the hydratable HTML which can be used in pages, and then create a JS file which hydrates that HTML.

**Comment by oscarotero** [comment]
I'm not sure if this is easy to implement. Remember that this is not a framework based SSG (unlike Gatsby, Next or Nuxt).
If it can be added easily using a plugin, I can consider it (I'm not an expert of React or Vue). Do you have any idea of how implement this?

**Comment by shadowtime2000** [comment]
This should be relatively easy to implement, considering how we just need to use `site.pages.push` to create a JS file. I am just wondering if plugins like the bundling one were implemented, would they process the JS file? We would need to figure out how to add a `script` tag with the `src` set to the JS file to the HTML file.

**Comment by JordanShurmer** [comment]
I'm interested in using Svelte on my site, which I recently converted to Lume. So, I may look into this sort of feature soon

**Comment by oscarotero** [comment]
I've created this example of react app with server side rendering using the bundler plugin: https://github.com/lumeland/react-todo
