### ISSUE TITLE
Remove `page.dest`.

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#290]
Currently, the `Page` class has the `dest` property with info about the destination.

The `dest` value must be in sync with the `url` value. For example, a page with the url `/foo/` will have the following dest:

```js
{
  path: "/foo/index",
  ext: ".html"
}
```

This is why we have the `page.updateDest()` function, that change not only the `dest` value of the page but also regenerate the url  accordingly.

The problem is this only work by changing the `dest` property, but not the `url`. If the `url` of a page is changed directly, the `dest` keeps the old value.

I think `dest` is a redundant value. It should be calculated only at saving time, according to the page's `url`. So we have a single source of truth that processors and preprocessors can change at any time.

**Comment by binyamin** [comment]
How about the other way around? Meaning, if `page.data.url` is never stored, only calculated. Maybe with a _getter_ which references `data.dest`.

My reasoning is twofold:
1. Lume's primary purpose is to generate a website, and write it to disk. It _can_ be used as a server, but it's really a static-site **generator**.
2. It sounds easier to tell plugins to edit `page.dest`, which is always either a `string` or `false`. If plugins try editing `page.data.url`, they might get a function by accident, since the user can specify a function for `page.data.url`.

**Comment by oscarotero** [comment]
It's more difficult and probably confusing for the users.

- People are used to define the `url` variable and use this variable in the templates. `page.dest` is an internal value.
- Getters for dynamic values are problematic in some template engines (like nunjucks). 
- The functions of the `url` values are invoked very early, plugins never get the function.

I'm aware of the multitype problem of `url`. Ideally it should allow only `string` and maybe allowing `false` was a bad idea. I'm thinking of removing this in Lume 2.0 and use a plugin or something to filter the pages that you don't want to export.

**Comment by oscarotero** [comment]
Done in v2 branch
