### ISSUE TITLE
Search plugin: support logical NOT

### ISSUE THREAD

**Issue by kwaa** [lumeland/lume#406]
### Discussed in https://github.com/lumeland/lume/discussions/405

<div type='discussions-op-text'>

<sup>Originally posted by **kwaa** March 31, 2023</sup>
I use [my own Frontmatter format](https://fff.js.org), where [`flags: ['unlisted']`](https://fff.js.org/concepts/flags.html) means that this post is not included in the list.

So how do I accurately search for flags that contain unlisted? [The search plugin's documentation](https://lume.land/plugins/search/) doesn't seem to indicate this, or maybe it doesn't support it yet.</div>

In this discussion I proposed `flags!*=unlisted`, but the logical NOT is more general.

Example:

```
category^=A => !category^=A
category$=B => !category$=B
title*=security => !title*=security
level>2 => !level>2
```

**Comment by oscarotero** [comment]
Ok, it makes sense.

I just commited a first version. You can test it after updating Lume to the latest development version (`deno task lume upgrade --dev`).

It supports both versions: `category!^=A` and `!category^=A` are equivalents.

The reason is the NOT operator of `=` is `!=`, so it would be a bit confusing to have a different syntax for the other operators. Now you can do `!category=A` as an alternative way to `category!=A`.

**Comment by kwaa** [comment]
> Ok, it makes sense.
> 
> I just commited a first version. You can test it after updating Lume to the latest development version (`deno task lume upgrade --dev`).
> 
> It supports both versions: `category!^=A` and `!category^=A` are equivalents.
> 
> The reason is the NOT operator of `=` is `!=`, so it would be a bit confusing to have a different syntax for the other operators. Now you can do `!category=A` as an alternative way to `category!=A`.

`!flags*=unlisted` and `flags!*=unlisted` have been tested to work! 🚀
