### ISSUE TITLE
Add option for specifying the init directory

### ISSUE THREAD

**Issue by echoptic** [lumeland/lume#417]
### Enter your suggestions in details:

I was surprised when i saw that i cant specify the init directory by adding the directory name after the init script like this:
`deno run -Ar https://deno.land/x/lume/init.ts <init directory name>`, and was not asked for the init directory when specifying the options in the init script. Maybe theres a way to do this, but i didnt see it

**Comment by oscarotero** [comment]
Yeah, this option is not available and it's a great idea. I guess if the directory doesn't exist, Lume should create it, right?
I like it as a CLI argument (I wouldn't include more questions).

**Comment by echoptic** [comment]
Yeah I think if it doesnt exist it should create it, and if it exists then print the error that the directory already exists and exit the cli

**Comment by echoptic** [comment]
If you change your mind about the question, maybe it could ask at the end something like `This directory is not empty? Do you want to continue?`.

**Comment by oscarotero** [comment]
Why the directory must be empty? `lume init` should work like `npm init`, `git init` or any other init script. You can use it to convert your existing site (built with other tool) to Lume. The only thing it does is to generate a couple of new files (`_config.ts` and `deno.json`).

I think you are thinking of `git clone` that requires an empty folder because there can be conflicts. But `init` is not the same.

**Comment by echoptic** [comment]
You have a point, even if the directory is not empty its not a big deal since only 2 files are created.

**Comment by oscarotero** [comment]
Released in 1.17.2
