### ISSUE TITLE
Dots in filenames lead to missing `.html` extension

### ISSUE THREAD

**Issue by not-my-profile** [lumeland/lume#430]
Like any other static-site generator Lume by default processes `foo.md` to `foo/index.html`. However if the filename contains a dot, e.g. `foo.bar.md` then Lume currently writes the HTML to `foo.bar` ... rather than writing to `foo.bar/index.html` as you would expect (case in point Jekyll and Eleventy and I'd assume most other static-site generators behave such by default).

It's worth noting that setting `prettyUrls: false` doesn't change the Lume behavior: it still writes the HTML to `foo.bar` rather than `foo.bar.html`, as you would expect. The relevant code appears to be the `getUrl` function in `core/source.ts`.

While changing the Lume default behavior regarding this would be a breaking change, I'd consider conforming to user expectations and common practice to be enough justification.

As a workaround you can currently [specify a relative URL](https://lume.land/docs/creating-pages/urls/#relative-urls) in the page frontmatter, such as `url: ./foo.bar/`.

**Comment by not-my-profile** [comment]
Right that makes sense if the last extension is a template extension such as `.njk` but it doesn't make sense for `.md` as the last extension as far as I can tell. So perhaps we could introduce some distinction?

**Comment by not-my-profile** [comment]
For the vary rare case that you actually want an `.md` file to produce a non-HTML file you can just specify the `url` in the YAML front matter. I think it's much more common to have a regular `.md` file with another dot in the filename.

**Comment by oscarotero** [comment]
Yes, my example was very exaggerated. Other more common example is if you don't want to have pretty urls for a specific file. For example, it's common the page to show in case of 404 errors is `404.html`, so you can create this page with `404.html.md`.

Anyway, the thing is it's easier to simply say "If the filename contains an extension, it's used as the output extension, otherwise, the html extension is used". 

If you have to add "...except for some extensions like md or pug that are formats intended to output html, so the extension in the filename will be ignored", this introduces some cognitive load in how Lume works and make its behavior less predictable.

Maybe is this a bad design choice? Perhaps, I don't know. To me, a file shouldn't have a dot in the name, because this is introduces some ambiguity. You can request the url `/foo/bar.png` expecting a png file but it opens the html page `/foo/bar.png/index.html`.

Anyway, keep in mind that this is the default way to generate url by Lume. If you want to change this behavior, it's very easy: just [create a `url` function](https://lume.land/docs/creating-pages/urls/#urls-as-functions) in the `/_data.js` file with your own implementation. For example:

```js
export function url (page) {
  return `./${page.src.slug}/`;
}
```

**Comment by not-my-profile** [comment]
> so you can create this page with `404.html.md`

I believe file extensions should describe the content of the file. I'd consider conflating actual file extensions describing the content of the file with file extensions describing the output format of some conversion process to be an anti-pattern. I'd consider any `.html.md` file to be confusing.

> this introduces some cognitive load in how Lume works and make its behavior less predictable

What is more predictable?

(A)

* `foo.md` -> `foo/index.html`
* `foo.bar.md` -> `foo.bar`
* `foo.bar.baz.md` -> `foo.baz`

or (B)?

* `foo.md` -> `foo/index.html`
* `foo.bar.md` -> `foo.bar/index.html`
* `foo.bar.baz.md` -> `foo.bar.baz/index.html`

A) is the current default behavior of Lume and B) is the default behavior of Jekyll and Eleventy. I find B) to be much more predictable.  (Granted that this is particularly true because in A3 Lume currently omits the `.bar` from the output filename, which is caused by the slug regex.)

> To me, a file shouldn't have a dot in the name, because this is introduces some ambiguity. You can request the url `/foo/bar.png` expecting a png file but it opens the html page `/foo/bar.png/index.html`.

Correct, you cannot assume a file type just from a URL ... this however is absolutely not a problem because web browsers determine the file type via the `Content-Type` HTTP header. Note that even if the default Lume behavior is changed, there is nothing stopping you from still avoiding dots in your filenames, if you prefer it that way.

On the contrary the current Lume default behavior poses an inconvenience to any user that wants to e.g. mention a version number in a file name, something even the Lume website does: https://lume.land/blog/posts/lume-1.17.0-release-notes

**Comment by oscarotero** [comment]
Okay, let's mimic the Jekyll / Eleventy behavior but I don't want to introduce a breaking change now. 
I'm going to put this on hold until Lume 2.0 that will introduce many breaking changes.

**Comment by oscarotero** [comment]
Fixed in the v2 branch.
