### ISSUE TITLE
Import NPM modules using ranges

### ISSUE THREAD

**Issue by binyamin** [lumeland/lume#472]
### Summary
When importing an NPM module, use a caret range (ie. `npm:preact@^10.16.0`). If a user has another compatible version of the module installed, Deno will just use that one instead of downloading another one. In other words, Deno's npm specifiers support semver ranges, so let's use them.

### Notes

Esbuild imports should probably use a tilde, so only patch updates will be affected, because [esbuild makes breaking changes in minor updates](https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0190).

#### Syntax
- caret "^" allows minor & patch updates
- tilde "~" only allows patch updates

**Comment by oscarotero** [comment]
For now, I prefer to continue using fixed versions. It's much more stable and easy to debug. I know Deno is moving toward semver compatibility (as announced for Deno 2.0) but I'm not fully convinced about this change and rather to wait.

**Comment by binyamin** [comment]
I haven't read the news about Deno 2.0. I did some testing, and ever since Deno stabilized NPM specifiers in v1.28.0, it correctly resolves semver in NPM specifiers.

**Comment by oscarotero** [comment]
When I mention stability, I'm not referring to Deno but the packages in general. One of the good things of Lume is the simplicity. If you want to use postcss, just import the plugin and use it. You don't need to worry about which version is used or if you need to update it because a minor release just came out.

Using fixed versions allows to test Lume in a reliable way. Ranges can introduce new bugs or inconsitencies with the Lume plugin, even in patch updates. Every time a new version of Lume is released, all dependencies are updated and tested ([using udd](https://github.com/hayd/deno-udd)). In the edge case that you need a different version, it's possible to patch it with the import maps.

Maybe in the future I change my mind, but for now I'd rather to continue using fixed versions.
If you want to take a look what's coming to Deno 2.0, this video explains it well: https://youtu.be/5DX49vzLfqw?si=hkoKe3EWuHeez27K&t=820
