### ISSUE TITLE
Lume components don't render in JSX pages as expected

### ISSUE THREAD

**Issue by cafour** [lumeland/lume#554]
### Version

2.0.3

### Platform

Windows

### What steps will reproduce the bug?

By following the button sample at https://lume.land/docs/core/components, I end up with `index.jsx` and `_components/button.vto` (see [lume-components.zip](https://github.com/lumeland/lume/files/13939605/lume-components.zip)).

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

I expect `index.jsx` to produce this `index.html`:
```html
<!DOCTYPE html>
<html><body><h1>Welcome to my site.</h1><button class="button">Login<button>
</body></html>
```

### What do you see instead?

Instead the tags in `button.vto` get HTML-escaped, producing:
```html
<!DOCTYPE html>
<html><body><h1>Welcome to my site.</h1>&lt;button class=&quot;button&quot;&gt;Login&lt;/button&gt;
</body></html>
```

### Additional information

The same happens if I implement the button component using a js module. However, when I use JSX the button is rendered correctly.

I'm not an expert on JSX by any means. I couldn't even figure out how to make it output raw HTML without involving an unnecessary `<div>` wrapper with `dangerouslySetInnerHTML` but since the docs say that _"Lume components can be used like React components if you're using the JSX plugin:"_, I'd assume Lume would handle the raw HTML output for me. (Or maybe the docs should be more specific and say that this works correctly only when _"...the component is using the JSX plugin..."_.

P.S.: I really enjoy using Lume and have been doing so for months now. Thanks! :3

**Comment by oscarotero** [comment]
You're right and the documentation should clarify this. Components work well if you're using JSX components inside a text-based template engine (like JSX button inside a Vento page) or JSX components in JSX templates.

What don't work well is text-based components inside JSX template engines (like in your example, a Vento component inside a JSX page), because strings are automatically escaped in JSX.

I didn't found a good way to fix that and probably the `div` wrapper is be best solution ATM.
