### ISSUE TITLE
How should `search.pages("foo,bar")` work?

### ISSUE THREAD

**Issue by valtlai** [lumeland/lume#74]
Should `search.pages("foo,bar")` find the pages having both a `foo` and `bar` tag (like `tags&=foo,bar`) or the pages having a `foo,bar` tag (like `tags*=foo,bar`)? The latter is the current behavior.

**Comment by oscarotero** [comment]
Spaces are the way to differentiate tags. To search pages with both tags, it should be `"foo bar"`. This was inspired by html `class` attribute in which `<div class="foo,bar">` is a `div` with one class named `foo,bar` not two classes.

The things got a bit complicated when I've introduced the ability to search by other properties with operators, so I had to add a way to search by several values in an array (to support the initial feature of searching by multiple tags), so introduced the comma. But this syntax is designed to be after an operator.

How should work `search.pages("one,two three")`? I think it should search pages with two tags: `one,two` and `three`, and it's equivalent to `search.pages("tags&='one,two',three")` (if quotes were supported). At this moment, there's no support to quotes in the comma-separated values, it could be implemented but I wanted to keep things simple for performance reasons.

**Comment by valtlai** [comment]
I’m wondering could we simplify this:

https://github.com/lumeland/lume/blob/f50f509f20a1a7329264e653f2d3c009a4afe909/helpers/search.js#L82-L86

To this:

```js
arg = "tags*=" + arg;
```

Currently, the `*=` operator also works with arrays and I think that’s nice even if not originally intended.

**Comment by oscarotero** [comment]
So you're proposing that searching for `foo bar` would be equivalent to `tags*=foo tags*=bar` instead `tags&=foo,bar` right? so we don't need the `&=` operator.

It makes sense.

We can even simplify more, removing the `|=` operator and use the pipe to separate values for the OR: `tags*=foo|bar`.

**Comment by oscarotero** [comment]
Ok, I've refactored the search engine to simplify things and give more flexibility:

- `foo bar` Search pages with these two tags
  - Equivalent to `tags*=foo tags*=bar`
- `foo|bar` Search pages with at least one of these two tags
  - Equivalent to `tags*=foo|bar`
- `title=foo` Search pages with the title `foo`
- `title=foo|bar` Search pages with the title `foo` or `bar`

Operators `&=` and `|=` are removed because they are not needed with this new syntax.

**Comment by valtlai** [comment]
That looks very good. It feels simpler and is still more flexible because you can use alternatives (`|`) with all the operators.

Should the string matching be case-sensitive or would it be more useful to make it case-insensitive? In the latter case, `title*=foo` would match `Foo bar baz`, which makes sense to me.

**Comment by oscarotero** [comment]
I'd leave them case-sensitive to simplify the code and avoid .toLowerCase() everywhere.

I'm also thinking in numbers. In yaml, any numeric value is converted to integer or float. This makes that searching by `order=12` won't return any value because the comparison is strict. For now, only "true" and "false" strings are converted to `true` and `false` booleans. Maybe it should do the same with numeric values. And it makes me think in `<` and `>` operator to search `order>12`.

**Comment by valtlai** [comment]
Yeah, I agree that number comparisons should be possible. Maybe we also need the `<=` and `>=` operators in addition to `<` and `>` you proposed.

**Comment by oscarotero** [comment]
Yes, dates would be great too.

I have been looking to how yaml parser convert the values to integer, boolean, date, etc. But it's too complicated (look for example integer conversion: https://deno.land/std@0.95.0/encoding/_yaml/type/int.ts)

Your solution of `isFinite()` is much more simple and enough for this case.

**Comment by oscarotero** [comment]
Updated search to add support for date and datetime. I'm closing this.
